### PR TITLE
Add check for msdcs dns records.

### PR DESCRIPTION
**Pull request by JakeDEvans**
Adding a simple DNS check to ensure that all replicas either have or have not done ad-trust-install. (could cause issues with one-way trusts and authentication)

### CODE REVIEW

**Comment by JakeDEvans** [comment]
rebase or just no?...

**Comment by peterpakos** [comment]
Please, if you don't mind, re-raise it on master branch. Thanks.

**Comment by JakeDEvans** [comment]
changed target back to master

**Comment by peterpakos** [comment]
This has now been merged in.

**Pull request merged**
